channels:
  - conda-forge

dependencies:
  - python=3.9.1
  - pip=20.1
  - pip:
      - rpaframework==10.0.6
      - requests==2.25.1
      - pandas==1.2.4
      - PyMuPDF==1.18.14
      - XlsxWriter==1.4.3
